site_name: MAP Odoo User Manual
site_url: https://mapitds.github.io/odoo-user-manual/

theme:
  name: material
  # language: id
  custom_dir: override
  palette:
    # Konfigurasi warna (kita pakai Indigo khas Odoo Enterprise)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mode Gelap
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mode Terang
  features:
    # - navigation.tabs        # Menu utama di bagian atas
    - navigation.sections      # Sub-menu rapi di samping
    - navigation               # Sub-menu bisa diperluas
    - navigation.indexes
    - navigation.instant
    - search.suggest           # Rekomendasi pencarian otomatis
    - search.highlight         # Efek stabilo pada teks yang dicari

# Mengaktifkan fitur kotak informasi berwarna (Admonitions)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  # - git-authors
  - git-committers:
      repository: mapitds/odoo-user-manual
      branch: main
  - git-committers:
      repository: mapitds/odoo-user-manual
      branch: sa-main
  # - i18n:
  #     default_language: id
  #     languages:
  #       - link: /id/
  #         locale: id
  #         name: Indonesian
  #         default: true
  #         build: true
  #       - link: /en/
  #         locale: en
  #         name: English
  #         default: false
  #         build: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      locale: id
      timezone: Asia/Jakarta
      fallback_to_build_date: true

# --- Pastikan bagian extra diatur seperti ini ---
extra:
  generator: false
  # alternate:
  #   - name: Indonesian
  #     link: /id/
  #     lang: id
  #   - name: English
  #     link: /en/
  #     lang: en

extra:
  assets:
    - icon_modul

extra_css:
  - stylesheets/extra.css

copyright: |
  <div class="custom-footer">
    <span>Copyright &copy; 2026 <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">CareSys</a> &mdash; Powered by <a href="https://github.com" target="_blank" rel="noopener">GitHub</a></span>
    <span>Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">Material for MkDocs</a></span>
  </div>

# Struktur Navigasi Menu Web Anda
nav:
  - Home : index.md

  - Sales Department : 
    - "🛃 Modules":
      - Negotiation Sheet : dept_sales/negotiation_sheet.md
      - Sales : dept_sales/sales_quotation.md
      - Sales Target : dept_sales/sales_target.md
  
  - Purchase Department :
    - "🛃 Modules":
      - Purchase Request : purchase/purchase_request.md
      - Purchase Order : purchase/purchase_order.md

  - Warehouse Department :
    - "🛃 Modules":
      - Inventory : dept_who/inventory.md
      - Receipts Order : dept_who/inventory_ri.md
      - Delivery Order : dept_who/inventory_do.md
      - Internal Transfer : dept_who/internal_transfer.md
  
  - Additional Modules :
    - "🛃 Productivity":
      - Timesheet : additional_modules/timesheet.md
      - Project : additional_modules/project.md
      - Helpdesk : additional_modules/helpdesk.md
      - Knowledge : additional_modules/knowledge.md
      - Calendar : additional_modules/calendar.md
      - Notes : additional_modules/notes.md
      - Discuss : additional_modules/discuss.md
      - Survey : additional_modules/survey.md
      - Events : additional_modules/events.md

  - Reporting : 
    - Accounting : additional_modules/accounting.md
    - Inventory : dept_who/inventory.md