site_name: MAP Odoo User Manual
site_url: https://mapitds.github.io/odoo-user-manual/

theme:
  name: material
  custom_dir: override
  palette:
    # Konfigurasi warna (kita pakai Indigo khas Odoo Enterprise)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mode Gelap
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mode Terang
  features:
    # - navigation.tabs          # Menu utama di bagian atas
    - navigation.sections      # Sub-menu rapi di samping
    - navigation.expand        # Sub-menu bisa diperluas
    - navigation.indexes
    - search.suggest           # Rekomendasi pencarian otomatis
    - search.highlight         # Efek stabilo pada teks yang dicari

# Mengaktifkan fitur kotak informasi berwarna (Admonitions)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: datetime
      locale: id
      timezone: Asia/Jakarta
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css

extra:
  assets:
    - icon_modul

# Struktur Navigasi Menu Web Anda
nav:
  - Home: index.md

  - Sales Department : 
    - Modules :
      - Negotiation Sheet : negotiation_sheet/negotiation_sheet.md
      - Sales : sales/sales_quotation.md
  
  - Purchase Department :
    - Modules :
      - Purchase Request : purchase/purchase_order.md
      - Purchase Order : purchase/request_for_quotation.md

  - Inventory Department :
    - Modules :
      - Inventory : inventory/inventory.md
      - Receipts Order : inventory/inventory_ri.md
      - Delivery Order : inventory/inventory_do.md
      - Internal Transfer : inventory/internal_transfer.md
      - Scrap : inventory/scrap.md