name: publish-docs
on:
  push:
    branches:
      - main # atau master, sesuaikan dengan nama branch utama Anda

permissions:
  contents: write

jobs:
  deploy:
    if: github.actor == 'bangjc'
    runs-on: ubuntu-latest
    steps:
      # Mengambil seluruh file proyek + riwayat log Git (wajib untuk plugin git-revision)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache

      # Menginstal tema utama dan seluruh plugin yang Anda pakai di mkdocs.yml
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-static-i18n

      # Jalankan deploy otomatis ke GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
